### ISSUE TITLE
Deploy GN customization w/ Jenkins

### ISSUE THREAD

**Issue by etj** [geosolutions-it/C024-CMF#3]
As discussed on skype, the files in this repo are an overlay on the geonetwork.war file.

We have 2 options to use these files:
- expand the geonetwork.war file, copy the files on the expanded dir and rezip back the war file, and make tomcat deploy the new war
- deploy the war file, copy the overlay files in the webapps/geonetwork directory

**Comment by randomorder** [comment]
what's the project? please add an estimate @giacomoc92

**Comment by conjame** [comment]
Project code: C024-2020-PROV_FI-GN_RNDT

**Comment by conjame** [comment]
I have updated the [job](https://build.geo-solutions.it/jenkins/job/Build_GeoNetwork-RNDT-3.10.x-rndt3/configure) to repack the war with the files from https://github.com/geosolutions-it/C024-CMF.git

![image](https://user-images.githubusercontent.com/49372260/99544497-aab87700-29b4-11eb-9c75-fb362384853a.png)

@etj
